apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kaniko-build-task
spec:
  params:
    - name: image-url
      type: string
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:latest
      args:
        - "--dockerfile=/workspace/output/Dockerfile"
        - "--context=/workspace/output"
        - "--destination=$(params.image-url)"
