apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: clone-task
spec:
  params:
    - name: repo-url
      type: string
  steps:
    - name: clone
      image: alpine/git
      script: |
        #!/bin/sh
        git clone $(params.repo-url) /workspace/output
