apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: open-flights-pipeline
spec:
  params:
    - name: repo-url
      type: string
    - name: image-url
      type: string
  tasks:
    - name: clone-repo
      taskRef:
        name: clone-task
    - name: build-image
      runAfter:
        - clone-repo
      taskRef:
        name: kaniko-build-task
