---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
  - port: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: openflights
spec:
  selector:
    app: openflights
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP
