apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openflights
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:yourusername/open-flights.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
